In [1]:
import numpy as np

In [7]:
arr1 = np.array([0, 10, 20, 30, 40, 50])
arr2 = np.array([10, 30, 50, 70, 90])

In [8]:
common_elements = arr1[np.isin(arr1, arr2)]

In [23]:
#with intersect1d method
arr1 = np.array([0, 10, 20, 30, 40, 50])
arr2 = np.array([10, 30, 50, 70, 90])
common_elements = np.intersect1d(arr1, arr2)
print(common_elements)


[10 30 50]


In [9]:
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Common Elements:", common_elements)

Array 1: [ 0 10 20 30 40 50]
Array 2: [10 30 50 70 90]
Common Elements: [10 30 50]


In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [11]:
row_means = arr.mean(axis=1)
result = arr - row_means.reshape(-1, 1)

In [12]:
print("Means of each row:", row_means)
print("\nOriginal Array:\n", arr)
print("\nArray after subtracting row means:\n", result)

Means of each row: [2. 5. 8.]

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after subtracting row means:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_means = arr.mean(axis=1)
result = arr - row_means.reshape(-1, 1)

In [14]:
print("Means of each row:", row_means)
print("\nOriginal Array:\n", arr)
print("\nArray after subtracting row means:\n", result)

Means of each row: [2. 5. 8.]

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after subtracting row means:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [15]:
arr = np.arange(16).reshape(4, 4)
first_half = arr[:2, :]
second_half = arr[2:, :]
swapped_arr = np.vstack((second_half, first_half))

In [16]:
print("Original Array:\n", arr)
print("\nSwapped Array:\n", swapped_arr)

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Swapped Array:
 [[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [17]:
np.random.seed(42) 
random_arr = np.random.randint(0, 100, size=15)
print("Original Random Array:", random_arr)

Original Random Array: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21]


In [18]:
sorted_indices = np.argsort(random_arr)
print("Indices that would sort the array:", sorted_indices)

Indices that would sort the array: [13  2  5 14 12  0  4  3  9  8  6  7 10  1 11]


In [19]:
indices_of_top_5 = sorted_indices[-5:]
print("\nIndices of the 5 largest values:", indices_of_top_5)


Indices of the 5 largest values: [ 6  7 10  1 11]


In [20]:
print("The 5 largest values are:", random_arr[indices_of_top_5])

The 5 largest values are: [82 86 87 92 99]


In [21]:
arr_with_duplicates = np.array([[0, 1, 2],
                                [3, 4, 5],
                                [0, 1, 2],
                                [6, 7, 8],
                                [3, 4, 5]])
print("Original Array with Duplicates:\n", arr_with_duplicates)

Original Array with Duplicates:
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [6 7 8]
 [3 4 5]]


In [22]:
unique_rows = np.unique(arr_with_duplicates, axis=0)
print("\nArray with Unique Rows Only:\n", unique_rows)


Array with Unique Rows Only:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
