In [1]:
import numpy as np

In [5]:
arr = np.array([10, 20, 30, 40, 50])


arr_min = arr.min()
arr_max = arr.max()

normalized_arr = (arr - arr_min) / (arr_max - arr_min)

In [6]:
print("Original Array:", arr)
print("Normalized Array:", normalized_arr)


Original Array: [10 20 30 40 50]
Normalized Array: [0.   0.25 0.5  0.75 1.  ]


In [12]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
random_arr = np.random.rand(10, 10)
min_val = random_arr.min()
max_val = random_arr.max()
mean_val = random_arr.mean()
std_val = random_arr.std()

In [16]:
print(f"Minimum value: {min_val:.4f}")
print(f"Maximum value: {max_val:.4f}")
print(f"Mean value: {mean_val:.4f}")
print(f"Standard Deviation: {std_val:.4f}")

Minimum value: 0.0137
Maximum value: 0.9918
Mean value: 0.4607
Standard Deviation: 0.2837


In [17]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_vector = np.array([10, 20, 30])
result = arr_2d + row_vector

In [18]:
print("2D Array:\n", arr_2d)
print("\nRow Vector:\n", row_vector)
print("\nResult of adding row vector:\n", result)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Vector:
 [10 20 30]

Result of adding row vector:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [20]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
col_data = np.array([10, 20, 30])
col_vector = col_data.reshape(3, 1)

In [21]:
result = arr_2d + col_vector

In [22]:
print("2D Array:\n", arr_2d)
print("\nColumn Vector:\n", col_vector)
print("\nResult of adding column vector:\n", result)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Column Vector:
 [[10]
 [20]
 [30]]

Result of adding column vector:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


In [25]:
arr_to_sort = np.array([[9, 4, 1],
                        [1, 5, 8],
                        [3, 2, 6]])
print("Original Array:\n", arr_to_sort)

sorted_indices = arr_to_sort[:, 1].argsort()
print("\nIndices to sort by column 1:", sorted_indices)

sorted_array = arr_to_sort[sorted_indices]
print("\nArray sorted by column 1:\n", sorted_array)

Original Array:
 [[9 4 1]
 [1 5 8]
 [3 2 6]]

Indices to sort by column 1: [2 0 1]

Array sorted by column 1:
 [[3 2 6]
 [9 4 1]
 [1 5 8]]
