In [1]:
import numpy as np

In [2]:
boolean_grid = np.full((3, 3), True)
print(boolean_grid)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 != 0]

In [5]:
print(odd_numbers)

[1 3 5 7 9]


In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1

In [7]:
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
reversed = arr_2d[:, ::-1]

In [9]:
print(reversed)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [10]:
arr = np.array([1, 8, 3, 6, 2, 9, 4, 7, 5])
indices = np.where(arr > 5)

In [11]:
print(indices)

(array([1, 3, 5, 7]),)


In [12]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
last_element = arr_2d[-1, -1]

In [13]:
print(last_element)

9
